export const DAILY_MAP = [
    {
        product_name: 'X Chews',
        href: 'x-chews',
        variant_index: 0,
        cadence: 'monthly',
        variant: '100iu/5mg',
        pharmacy: 'hallandale',
        price: 199,
    },
    {
        product_name: 'X Chews',
        href: 'x-chews',
        variant_index: 1,
        cadence: 'quarterly',
        variant: '100iu/5mg',
        pharmacy: 'hallandale',
        price: 399,
    },
    {
        product_name: 'X Chews',
        href: 'x-chews',
        variant_index: 2,
        cadence: 'biannually',
        variant: '100iu/5mg',
        pharmacy: 'hallandale',
        price: 599,
    },
    {
        product_name: 'X Melts',
        href: 'x-melts',
        variant_index: 0,
        cadence: 'monthly',
        variant: '100iu/5mg',
        pharmacy: 'hallandale',
        price: 199,
    },
    {
        product_name: 'X Melts',
        href: 'x-melts',
        variant_index: 1,
        cadence: 'quarterly',
        variant: '100iu/5mg',
        pharmacy: 'hallandale',
        price: 399,
    },
    {
        product_name: 'X Melts',
        href: 'x-melts',
        variant_index: 2,
        cadence: 'biannually',
        variant: '100iu/5mg',
        pharmacy: 'hallandale',
        price: 599,
    },
    {
        product_name: 'Tadalfil',
        href: 'tadalafil',
        variant_index: 0,
        cadence: 'monthly',
        variant: '5 mg',
        pharmacy: 'curexa',
        price: 79,
    },
    {
        product_name: 'Tadalfil',
        href: 'tadalafil',
        variant_index: 1,
        cadence: 'quarterly',
        variant: '5 mg',
        pharmacy: 'curexa',
        price: 139,
    },
    {
        product_name: 'Tadalfil',
        href: 'tadalafil',
        variant_index: 2,
        cadence: 'biannually',
        variant: '5 mg',
        pharmacy: 'curexa',
        price: 189,
    },
    {
        product_name: 'Tadalfil',
        href: 'tadalafil',
        variant_index: 3,
        cadence: 'monthly',
        variant: '10 mg',
        pharmacy: 'curexa',
        price: 81,
    },
    {
        product_name: 'Tadalfil',
        href: 'tadalafil',
        variant_index: 4,
        cadence: 'quarterly',
        variant: '10 mg',
        pharmacy: 'curexa',
        price: 143,
    },
    {
        product_name: 'Tadalfil',
        href: 'tadalafil',
        variant_index: 5,
        cadence: 'biannually',
        variant: '10 mg',
        pharmacy: 'curexa',
        price: 195,
    },
    {
        product_name: 'Tadalfil',
        href: 'tadalafil',
        variant_index: 6,
        cadence: 'monthly',
        variant: '20 mg',
        pharmacy: 'curexa',
        price: 84,
    },
    {
        product_name: 'Tadalfil',
        href: 'tadalafil',
        variant_index: 7,
        cadence: 'quarterly',
        variant: '20 mg',
        pharmacy: 'curexa',
        price: 147,
    },
    {
        product_name: 'Tadalfil',
        href: 'tadalafil',
        variant_index: 8,
        cadence: 'biannually',
        variant: '20 mg',
        pharmacy: 'curexa',
        price: 201,
    },
    {
        product_name: 'Peak Chews',
        href: 'peak-chews',
        variant_index: 0,
        cadence: 'monthly',
        variant: '7mg',
        pharmacy: 'empower',
        price: 109,
    },
    {
        product_name: 'Peak Chews',
        href: 'peak-chews',
        variant_index: 1,
        cadence: 'quarterly',
        variant: '7mg',
        pharmacy: 'empower',
        price: 259,
    },
    {
        product_name: 'Peak Chews',
        href: 'peak-chews',
        variant_index: 2,
        cadence: 'biannually',
        variant: '7mg',
        pharmacy: 'empower',
        price: 359,
    },
    {
        product_name: 'Rush Chews',
        href: 'rush-chews',
        variant_index: 0,
        cadence: 'monthly',
        variant: '36 mg',
        pharmacy: 'empower',
        price: 119,
    },
    {
        product_name: 'Rush Chews',
        href: 'rush-chews',
        variant_index: 1,
        cadence: 'quarterly',
        variant: '36 mg',
        pharmacy: 'empower',
        price: 259,
    },
    {
        product_name: 'Rush Chews',
        href: 'rush-chews',
        variant_index: 2,
        cadence: 'biannually',
        variant: '36 mg',
        pharmacy: 'empower',
        price: 369,
    },
    {
        product_name: 'Rush Chews',
        href: 'rush-chews',
        variant_index: 3,
        cadence: 'monthly',
        variant: '60 mg',
        pharmacy: 'empower',
        price: 121,
    },
    {
        product_name: 'Rush Chews',
        href: 'rush-chews',
        variant_index: 4,
        cadence: 'quarterly',
        variant: '60 mg',
        pharmacy: 'empower',
        price: 269,
    },
    {
        product_name: 'Rush Chews',
        href: 'rush-chews',
        variant_index: 5,
        cadence: 'biannually',
        variant: '60 mg',
        pharmacy: 'empower',
        price: 379,
    },
];

export const AS_NEEDED_MAP = [
    {
        product_name: 'Peak Chews',
        href: 'peak-chews',
        variant_index: 37,
        cadence: 'quarterly',
        variant: '10 mg',
        pharmacy: 'empower',
        price: 96,
    },
    {
        product_name: 'Peak Chews',
        href: 'peak-chews',
        variant_index: 38,
        cadence: 'biannually',
        variant: '10 mg',
        pharmacy: 'empower',
        price: 150,
    },
];
