version: '3.9'
services:
  app:
    build: .
    environment:
      - STRIPE_SK=${STRIPE_SK}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
    volumes:
      - .:/app
    command: npm test
  server:
    build: .
    environment:
      - STRIPE_SK=${STRIPE_SK}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
    volumes:
      - .:/app
    ports:
      - "3000:3000"