import {
    B12_INJECTION_PRODUCT_HREF,
    B12_MIC_INJECTION_PRODUCT_HREF,
    CGM_SENSOR_PRODUCT_HREF,
    FINASTERINE_AND_MINOXIDIL_SPRAY_PRODUCT_HREF,
    GLUTATHIONE_INJECTION_PRODUCT_HREF,
    GLUTATHIONE_NASAL_SPRAY_PRODUCT_HREF,
    GLUTATHIONE_PATCHES_PRODUCT_HREF,
    LOW_DOSE_NALTREXONE_PRODUCT_HREF,
    NAD_FACE_CREAM_PRODUCT_HREF,
    NAD_INJECTION_PRODUCT_HREF,
    NAD_NASAL_SPRAY_PRODUCT_HREF,
    NAD_PATCHES_PRODUCT_HREF,
    TADALAFIL_AS_NEEDED_PRODUCT_HREF,
    TADALAFIL_DAILY_PRODUCT_HREF,
} from '@/app/services/tracking/constants';

export const PRODUCTS_WITH_ONE_HYPHEN = [
    LOW_DOSE_NALTREXONE_PRODUCT_HREF,
    B12_INJECTION_PRODUCT_HREF,
    NAD_PATCHES_PRODUCT_HREF,
    NAD_INJECTION_PRODUCT_HREF,
    GLUTATHIONE_INJECTION_PRODUCT_HREF,
    GLUTATHIONE_PATCHES_PRODUCT_HREF,
    TADALAFIL_DAILY_PRODUCT_HREF,
    CGM_SENSOR_PRODUCT_HREF,
];

export const PRODUCTS_WITH_DOUBLE_HYPHEN = [
    NAD_FACE_CREAM_PRODUCT_HREF,
    GLUTATHIONE_NASAL_SPRAY_PRODUCT_HREF,
    NAD_NASAL_SPRAY_PRODUCT_HREF,
    B12_MIC_INJECTION_PRODUCT_HREF,
    TADALAFIL_AS_NEEDED_PRODUCT_HREF,
];

export const PRODUCTS_WITH_TRIPLE_HYPHEN = [
    FINASTERINE_AND_MINOXIDIL_SPRAY_PRODUCT_HREF,
];
