import {
    ClinicalNoteTemplate,
    ClinicalNoteTemplateOptionType,
} from '../clinical-note-template-latest-versions';

export const ED_TEMPLATE: ClinicalNoteTemplate = {
    version: 1,
    render: [
        {
            type: ClinicalNoteTemplateOptionType.MULTISELECT,
            default: true,
            values: [
                'Patient agrees to asynchronous encounter via intake and consented to telehealth consent. Patients identification confirmed via photo ID. Patient is determined to be appropriate for asynchronous care and is 18 or older',
                'Patient denies concomitant use of nitrates, "poppers."',
                'Patient denies serious heart, liver, or kidney problems.',
                'Patient denies pregnancy/breastfeeding.',
                'Patient is not on any CYP3A4 inhibitors.',
                'Medical history, current medications and allergies reviewed.',
                'Patient is a good candidate for ED medication.',
                'Patient is aware not to take other ED medication within 24 hours of taking requested medicationl',
                'Patient is counseled on potential side effects. ER/UC precautions given.',
            ],
        },
        {
            type: ClinicalNoteTemplateOptionType.MULTISELECT,
            default: false,
            title: 'Dx (Select all that apply): ',
            setting: 'Dx',
            values: [
                'N52.9 Male erectile dysfunction',
                'F52.4 Premature ejaculation',
                'None/Other (see note)',
            ],
        },
        {
            type: ClinicalNoteTemplateOptionType.SELECT,
            default: false,
            title: 'Medication Approved:',
            values: [
                'Generic Cialis (tadalafil)',
                'Generic Viagra (sildenafil)',
                'Sildenafil/tadalafil',
                'Sildenafil/oxytoxin',
                'Tadalafil/oxytocin',
                'Cialis',
                'Viagra',
                'None. Refer to PCP',
            ],
        },
        {
            type: ClinicalNoteTemplateOptionType.SELECT,
            default: false,
            title: 'Dose (select one)',
            values: [
                '10 mg as needed',
                '20 mg as needed',
                '5 mg daily',
                '10 mg daily',
                '8.5 mg daily',
                '36 mg daily',
                '100iu/5mg daily',
                '60 mg prn',
                '100iu/5mg prn',
                '5 mg prn',
                '10 mg prn',
                '25 mg prn',
                '50 mg prn',
                '81mg/12g prn',
                '100 mg prn',
                'N/A',
            ],
        },
        {
            type: ClinicalNoteTemplateOptionType.NOTE,
            values: [],
        },
    ],
};

export const ED_TEMPLATE_V2: ClinicalNoteTemplate = {
    version: 2,
    render: [
        {
            type: ClinicalNoteTemplateOptionType.MULTISELECT,
            default: true,
            values: [
                "Patient agrees to asynchronous encounter via intake and consented to telehealth consent. Pt's identification confirmed via photo ID. Pt is determined to be appropriate for asynchronous care and is 18 or older",
                'Patient denies concomitant use of nitrates, "poppers.".',
                'Patient denies serious heart, liver, or kidney problems.',
                'Patient is not on any CYP3A4 inhibitors.',
                'Medical history, current medications and allergies reviewed',
                'Patient is a good candidate for ED medication.',
                'Pt is aware not to take other ED medication within 24 hours of taking requested medication',
                'Patient is counseled on potential side effects. ER/UC precautions given.',
            ],
        },
        {
            type: ClinicalNoteTemplateOptionType.MULTISELECT,
            default: false,
            title: 'Dx (Select all that apply): ',
            setting: 'Dx',
            values: [
                'N52.9 Male erectile dysfunction',
                'F52.4 Premature ejaculation',
                'None/Other (see note)',
            ],
        },
        {
            type: ClinicalNoteTemplateOptionType.SELECT,
            default: false,
            title: 'Medication Approved:',
            values: [
                'Generic Cialis (tadalafil)',
                'Generic Viagra (sildenafil)',
                'Sildenafil/tadalafil',
                'Sildenafil/oxytoxin',
                'Tadalafil/oxytocin',
                'Cialis',
                'Viagra',
                'None. Refer to PCP',
            ],
        },
        {
            type: ClinicalNoteTemplateOptionType.SELECT,
            default: false,
            title: 'Dose (select one)',
            values: [
                '10 mg as needed',
                '20 mg as needed',
                '5 mg daily',
                '10 mg daily',
                '8.5 mg daily',
                '36 mg daily',
                '100iu/5mg daily',
                '60 mg prn',
                '100iu/5mg prn',
                '5 mg prn',
                '10 mg prn',
                '25 mg prn',
                '50 mg prn',
                '81mg/12g prn',
                '100 mg prn',
                'N/A',
            ],
        },
        {
            type: ClinicalNoteTemplateOptionType.MULTISELECT,
            default: true,
            title: '',
            values: [
                'Patient was provided information regarding medication instructions, precautions, side effects and lifestyle recommendations.',
            ],
        },
        {
            type: ClinicalNoteTemplateOptionType.NOTE,
            values: [],
        },
    ],
};
