import {
    B12_INJECTION_PRODUCT_HREF,
    GLUTATHIONE_INJECTION_PRODUCT_HREF,
} from '@/app/services/tracking/constants';
import {
    AB_TESTS_IDS,
    INTAKE_ROUTE,
    INTAKE_ROUTE_V3,
} from '../types/intake-enumerators';
import { PRODUCT_HREF } from '@/app/types/global/product-enumerator';

export const TOPNAV_ROUTES_NOT_TO_SHOW_BAR = [
    INTAKE_ROUTE.WEIGHT_LOSS_INTRO_1,
    INTAKE_ROUTE.WEIGHT_LOSS_INTRO_2,
    INTAKE_ROUTE.REGISTRATION,
    INTAKE_ROUTE.REASONS_TO_BELIEVE,
    INTAKE_ROUTE.WEIGHT_LOSS_INTRO_SCREEN,
    INTAKE_ROUTE.WEIGHT_LOSS_INTRO_OPTIONS,
    INTAKE_ROUTE.WEIGHT_LOSS_INTRO_GRAPH,
    INTAKE_ROUTE.WEIGHT_LOSS_INTRO_SPECIALISTS,
    INTAKE_ROUTE.START_WEIGHT_LOSS_JOURNEY,
    INTAKE_ROUTE.WEIGHT_LOSS_INTRO_QUESTION_1,
    INTAKE_ROUTE.WEIGHT_LOSS_INTRO_QUESTION_2,
    INTAKE_ROUTE.WEIGHT_LOSS_INTRO_QUESTION_3,
    INTAKE_ROUTE.WEIGHT_LOSS_INTRO_QUESTION_4,
    INTAKE_ROUTE.WEIGHT_LOSS_INFORM_1,
    INTAKE_ROUTE.WEIGHT_LOSS_INFORM_2,
    INTAKE_ROUTE.WEIGHT_LOSS_INFORM_3,
    INTAKE_ROUTE.WEIGHT_LOSS_STAT,
];

export const TOPNAV_PRODUCT_ROUTES_NOT_TO_SHOW_BAR = [
    GLUTATHIONE_INJECTION_PRODUCT_HREF,
    B12_INJECTION_PRODUCT_HREF,
];

export const CREATE_ACCOUNT_ROUTES = [
    INTAKE_ROUTE.WEIGHT_LOSS_INTRO_1,
    INTAKE_ROUTE.WEIGHT_LOSS_INTRO_2,
    INTAKE_ROUTE.REGISTRATION,
    INTAKE_ROUTE.GOOD_TO_GO,
    INTAKE_ROUTE.UNAVAILABLE_IN_AREA,
    INTAKE_ROUTE.STATE_SELECTION,
    INTAKE_ROUTE.DATE_OF_BIRTH,
];
export const TAKE_ASSESSMENT_ROUTES = ['question', 'patient-match'];
export const START_CARE_ROUTES = [
    INTAKE_ROUTE.ID_VERIFICATION,
    INTAKE_ROUTE.CHECKOUT,
    INTAKE_ROUTE.PRE_ID_VERIFICATION,
    INTAKE_ROUTE.PRODUCT_OVERVIEW,
    INTAKE_ROUTE.WEIGHT_LOSS_CHECKLIST,
    INTAKE_ROUTE.PRODUCT_OVERVIEW,
    INTAKE_ROUTE.SHIPPING_INFORMATION,
];

export const UNBLURRED_ROUTES = [
    INTAKE_ROUTE.NAD_BENEFITS,
    INTAKE_ROUTE.REGISTRATION,
    INTAKE_ROUTE.WEIGHT_LOSS_GRAPH,
    INTAKE_ROUTE.ID_VERIFICATION,
    INTAKE_ROUTE.PRODUCT_OVERVIEW,
    INTAKE_ROUTE.SHIPPING_INFORMATION,
    INTAKE_ROUTE.CHECKOUT,
    INTAKE_ROUTE.WEIGHT_LOSS_INTRO_SCREEN,
    INTAKE_ROUTE.ED_SELECTION,
];

//HEADSUP Routes declaration:
export const STANDARD_INTAKE_ROUTES: IntakeRouteSpecification = {
    1: {
        version: 1,
        route_array: [
            INTAKE_ROUTE.REGISTRATION,
            INTAKE_ROUTE.STATE_SELECTION,
            INTAKE_ROUTE.DATE_OF_BIRTH,
            INTAKE_ROUTE.DEMOGRAPHIC_INFORMATION,
            INTAKE_ROUTE.GOOD_TO_GO,
            INTAKE_ROUTE.QUESTIONS,
            INTAKE_ROUTE.PATIENT_MATCH,
            INTAKE_ROUTE.PRE_ID_VERIFICATION,
            INTAKE_ROUTE.ID_VERIFICATION,
            INTAKE_ROUTE.PRODUCT_OVERVIEW,
            INTAKE_ROUTE.SHIPPING_INFORMATION,
            INTAKE_ROUTE.CHECKOUT,
        ],
        ab_tests: [],
    },
};

export const ED_GLOBAL_INTAKE_ROUTES: IntakeRouteSpecification = {
    1: {
        version: 1,
        route_array: [
            INTAKE_ROUTE.ED_INTRO,
            INTAKE_ROUTE.REGISTRATION,
            INTAKE_ROUTE.STATE_SELECTION,
            INTAKE_ROUTE.DATE_OF_BIRTH,
            INTAKE_ROUTE.PRE_DEMOGRAPHIC,
            INTAKE_ROUTE.WEIGHT_LOSS_DEMOGRAPHICS,
            INTAKE_ROUTE.GREETING,
            INTAKE_ROUTE.UP_NEXT_3_HEALTH,
            INTAKE_ROUTE.QUESTIONS,
            INTAKE_ROUTE.ED_SELECTION,
            INTAKE_ROUTE.ED_PRE_ID,
            INTAKE_ROUTE.SHIPPING_INFORMATION,
            INTAKE_ROUTE.ID_VERIFICATION,
            INTAKE_ROUTE.ED_CHECKOUT,
        ],
        ab_tests: [],
    },
};

export const ED_X_PRODUCTS_INTAKE_ROUTES: IntakeRouteSpecification = {
    1: {
        version: 1,
        route_array: [
            INTAKE_ROUTE.ED_INTRO,
            INTAKE_ROUTE.REGISTRATION,
            INTAKE_ROUTE.STATE_SELECTION,
            INTAKE_ROUTE.DATE_OF_BIRTH,
            INTAKE_ROUTE.PRE_DEMOGRAPHIC,
            INTAKE_ROUTE.WEIGHT_LOSS_DEMOGRAPHICS,
            INTAKE_ROUTE.GREETING,
            INTAKE_ROUTE.UP_NEXT_3_HEALTH,
            INTAKE_ROUTE.QUESTIONS,
            INTAKE_ROUTE.ED_SELECTION,
            INTAKE_ROUTE.ED_PRE_ID,
            INTAKE_ROUTE.SHIPPING_INFORMATION,
            INTAKE_ROUTE.ID_VERIFICATION,
            INTAKE_ROUTE.ED_CHECKOUT,
        ],
        ab_tests: [],
    },
};

export const ED_PRODUCT_INTAKE_ROUTES: IntakeRouteSpecification = {
    1: {
        version: 1,
        route_array: [
            INTAKE_ROUTE.ED_INTRO,
            INTAKE_ROUTE.REGISTRATION,
            INTAKE_ROUTE.STATE_SELECTION,
            INTAKE_ROUTE.DATE_OF_BIRTH,
            INTAKE_ROUTE.PRE_DEMOGRAPHIC,
            INTAKE_ROUTE.WEIGHT_LOSS_DEMOGRAPHICS,
            INTAKE_ROUTE.GREETING,
            INTAKE_ROUTE.UP_NEXT_3_HEALTH,
            INTAKE_ROUTE.QUESTIONS,
            INTAKE_ROUTE.ED_MATCH_TRANSITION,
            INTAKE_ROUTE.ED_INDIVIDUAL_FREQUENCY_SELECTION,
            INTAKE_ROUTE.ED_PRODUCT_DISPLAY,
            INTAKE_ROUTE.ED_OPTION_SELECTION,
            INTAKE_ROUTE.ED_PRE_ID,
            INTAKE_ROUTE.SHIPPING_INFORMATION,
            INTAKE_ROUTE.ID_VERIFICATION,
            INTAKE_ROUTE.ED_CHECKOUT,
        ],
        ab_tests: [],
    },
};

export const RUSH_MELTS_INTAKE_ROUTES: IntakeRouteSpecification = {
    1: {
        version: 1,
        route_array: [
            INTAKE_ROUTE.ED_INTRO,
            INTAKE_ROUTE.REGISTRATION,
            INTAKE_ROUTE.STATE_SELECTION,
            INTAKE_ROUTE.DATE_OF_BIRTH,
            INTAKE_ROUTE.PRE_DEMOGRAPHIC,
            INTAKE_ROUTE.WEIGHT_LOSS_DEMOGRAPHICS,
            INTAKE_ROUTE.GREETING,
            INTAKE_ROUTE.UP_NEXT_3_HEALTH,
            INTAKE_ROUTE.QUESTIONS,
            INTAKE_ROUTE.ED_MATCH_TRANSITION,
            INTAKE_ROUTE.ED_PRODUCT_DISPLAY,
            INTAKE_ROUTE.ED_OPTION_SELECTION,
            INTAKE_ROUTE.ED_PRE_ID,
            INTAKE_ROUTE.SHIPPING_INFORMATION,
            INTAKE_ROUTE.ID_VERIFICATION,
            INTAKE_ROUTE.ED_CHECKOUT,
        ],
        ab_tests: [],
    },
};

// "primary test": this test has it's own route array or it's own question set version, or both
// since you can't have two different route arrays or question set versions for the same product, you can't run two primary tests at the same time
// "secondary test": agnostic to whichever primary test is running, does not have it's own route array or question set version
// secondary tests can be run in parallel with primary tests
export const SEMAGLUTIDE_ROUTES: IntakeRouteSpecification = {
    1: {
        version: 1,
        route_array: [
            INTAKE_ROUTE_V3.WEIGHT_LOSS_ACCOMPLISH_GOALS,
            INTAKE_ROUTE_V3.WEIGHT_LOSS_BMI,
            INTAKE_ROUTE_V3.WEIGHT_LOSS_DATA_PROCESSING,
            INTAKE_ROUTE_V3.WEIGHT_LOSS_GRAPH_PRE_SIGNUP,
            INTAKE_ROUTE_V3.REASONS_TO_BELIEVE, //<-- spring sale banner test splits here (secondary test)
            INTAKE_ROUTE_V3.WL_INTRO_SPECIALISTS, //<-- competitor comparison test splits here (primary test)
            INTAKE_ROUTE_V3.STATE_SELECTION,
            INTAKE_ROUTE_V3.DATE_OF_BIRTH,
            INTAKE_ROUTE_V3.GOOD_NEWS,
            INTAKE_ROUTE_V3.WEIGHT_LOSS_DEMOGRAPHICS, //<-- this is where question set version is set for a primary test
            INTAKE_ROUTE_V3.GREETING,
            INTAKE_ROUTE_V3.UP_NEXT_V3_WL,
            INTAKE_ROUTE_V3.QUESTIONS,
            INTAKE_ROUTE_V3.WEIGHT_LOSS_INTRO_3,
            INTAKE_ROUTE_V3.WEIGHT_LOSS_SUPPLY,
            INTAKE_ROUTE_V3.ORDER_SUMMARY,
            INTAKE_ROUTE_V3.WEIGHT_LOSS_REVIEWS,
            INTAKE_ROUTE_V3.PRE_ID_VERIFICATION,
            INTAKE_ROUTE_V3.ID_VERIFICATION,
            INTAKE_ROUTE_V3.SHIPPING_INFORMATION,
            INTAKE_ROUTE_V3.WEIGHT_LOSS_CHECKOUT, //<-- FOMO checkout test splits here (secondary test)
        ],
        ab_tests: [
            {
                name: 'WL Funnel No 6 Month Option',
                id: AB_TESTS_IDS.WL_FUNNEL_NO_6,
                version: 1,
                route_array: [
                    INTAKE_ROUTE.WEIGHT_LOSS_INTRO_1,
                    INTAKE_ROUTE_V3.WEIGHT_LOSS_INTRO_2,
                    INTAKE_ROUTE_V3.REASONS_TO_BELIEVE,
                    INTAKE_ROUTE_V3.WL_INTRO_SPECIALISTS,
                    INTAKE_ROUTE_V3.REGISTRATION,
                    INTAKE_ROUTE_V3.STATE_SELECTION,
                    INTAKE_ROUTE_V3.DATE_OF_BIRTH,
                    INTAKE_ROUTE_V3.GOOD_NEWS,
                    INTAKE_ROUTE_V3.WEIGHT_LOSS_DEMOGRAPHICS,
                    INTAKE_ROUTE_V3.GREETING,
                    INTAKE_ROUTE_V3.UP_NEXT,
                    INTAKE_ROUTE_V3.QUESTIONS,
                    INTAKE_ROUTE_V3.PATIENT_MATCH,
                    INTAKE_ROUTE_V3.WEIGHT_LOSS_GRAPH,
                    INTAKE_ROUTE_V3.WEIGHT_LOSS_INTRO_3,
                    INTAKE_ROUTE_V3.WEIGHT_LOSS_SUPPLY_NO_6,
                    INTAKE_ROUTE_V3.ORDER_SUMMARY,
                    INTAKE_ROUTE_V3.WEIGHT_LOSS_REVIEWS,
                    INTAKE_ROUTE_V3.PRE_ID_VERIFICATION,
                    INTAKE_ROUTE_V3.ID_VERIFICATION,
                    INTAKE_ROUTE_V3.SHIPPING_INFORMATION,
                    INTAKE_ROUTE_V3.WEIGHT_LOSS_CHECKOUT,
                ],
            },
            // {
            //     name: 'WL Funnel Show ID After Checkout',
            //     id: AB_TESTS_IDS.WL_SHOW_ID_AFTER_CHECKOUT,
            //     version: 1,
            //     route_array: [
            //         INTAKE_ROUTE.WEIGHT_LOSS_INTRO_1,
            //         INTAKE_ROUTE_V3.WEIGHT_LOSS_INTRO_2,
            //         INTAKE_ROUTE_V3.REASONS_TO_BELIEVE,
            //         INTAKE_ROUTE_V3.WL_INTRO_SPECIALISTS,
            //         INTAKE_ROUTE_V3.REGISTRATION,
            //         INTAKE_ROUTE_V3.STATE_SELECTION,
            //         INTAKE_ROUTE_V3.DATE_OF_BIRTH,
            //         INTAKE_ROUTE_V3.GOOD_NEWS,
            //         INTAKE_ROUTE_V3.WEIGHT_LOSS_DEMOGRAPHICS,
            //         INTAKE_ROUTE_V3.GREETING,
            //         INTAKE_ROUTE_V3.UP_NEXT,
            //         INTAKE_ROUTE_V3.QUESTIONS,
            //         INTAKE_ROUTE_V3.PATIENT_MATCH,
            //         INTAKE_ROUTE_V3.WEIGHT_LOSS_GRAPH,
            //         INTAKE_ROUTE_V3.WEIGHT_LOSS_INTRO_3,
            //         INTAKE_ROUTE_V3.WEIGHT_LOSS_SUPPLY,
            //         INTAKE_ROUTE_V3.ORDER_SUMMARY,
            //         INTAKE_ROUTE_V3.WEIGHT_LOSS_REVIEWS,
            //         INTAKE_ROUTE_V3.SHIPPING_INFORMATION,
            //         INTAKE_ROUTE_V3.WEIGHT_LOSS_CHECKOUT,
            //         INTAKE_ROUTE_V3.PRE_ID_POST_CO,
            //         INTAKE_ROUTE_V3.ID_VERIFICATION_POST_CO,
            //     ],
            // },
            {
                name: 'WL Funnel Show Graph First Flow', //Ro Flow
                id: AB_TESTS_IDS.WL_SHOW_GRAPH_FIRST,
                version: 1,
                route_array: [
                    INTAKE_ROUTE_V3.WEIGHT_LOSS_ACCOMPLISH_GOALS,
                    INTAKE_ROUTE_V3.WEIGHT_LOSS_BMI,
                    INTAKE_ROUTE_V3.WEIGHT_LOSS_DATA_PROCESSING,
                    INTAKE_ROUTE_V3.WEIGHT_LOSS_GRAPH_PRE_SIGNUP,
                    INTAKE_ROUTE_V3.REASONS_TO_BELIEVE,
                    INTAKE_ROUTE_V3.WL_INTRO_SPECIALISTS,
                    INTAKE_ROUTE_V3.STATE_SELECTION,
                    INTAKE_ROUTE_V3.DATE_OF_BIRTH,
                    INTAKE_ROUTE_V3.GOOD_NEWS,
                    INTAKE_ROUTE_V3.WEIGHT_LOSS_DEMOGRAPHICS,
                    INTAKE_ROUTE_V3.GREETING,
                    INTAKE_ROUTE_V3.UP_NEXT,
                    INTAKE_ROUTE_V3.QUESTIONS,
                    INTAKE_ROUTE_V3.WEIGHT_LOSS_INTRO_3,
                    INTAKE_ROUTE_V3.WEIGHT_LOSS_SUPPLY,
                    INTAKE_ROUTE_V3.ORDER_SUMMARY,
                    INTAKE_ROUTE_V3.WEIGHT_LOSS_REVIEWS,
                    INTAKE_ROUTE_V3.SHIPPING_INFORMATION,
                    INTAKE_ROUTE_V3.WEIGHT_LOSS_CHECKOUT,
                    INTAKE_ROUTE_V3.PRE_ID_POST_CO,
                    INTAKE_ROUTE_V3.ID_VERIFICATION_POST_CO,
                ],
            },
            {
                name: 'Hers Semaglutide WL Funnel',
                id: AB_TESTS_IDS.WL_HERS_FUNNEL,
                version: 1,
                route_array: [
                    INTAKE_ROUTE_V3.START_WEIGHT_LOSS_JOURNEY_V3,
                    INTAKE_ROUTE_V3.WEIGHT_LOSS_GOAL_HERS,
                    INTAKE_ROUTE_V3.WEIGHT_LOSS_GOAL_HERS_TRANSITION,
                    INTAKE_ROUTE_V3.WEIGHT_LOSS_INFOGRAPHIC_HERS,
                    INTAKE_ROUTE_V3.WEIGHT_LOSS_PROFILE_START,
                    INTAKE_ROUTE_V3.STATE_SELECTION_HERS,
                    INTAKE_ROUTE_V3.GOOD_NEWS,
                    INTAKE_ROUTE_V3.PRE_DATE_OF_BIRTH,
                    INTAKE_ROUTE_V3.PRE_QUESTIONS,
                    INTAKE_ROUTE_V3.REGISTRATION,
                    INTAKE_ROUTE_V3.WEIGHT_LOSS_DEMOGRAPHICS,
                    INTAKE_ROUTE_V3.UP_NEXT,
                    INTAKE_ROUTE_V3.QUESTIONS,
                    INTAKE_ROUTE_V3.BMI_SUMMARY,
                    INTAKE_ROUTE_V3.PREVIEW_TREATMENT,
                    INTAKE_ROUTE_V3.PRE_TREATMENT,
                    INTAKE_ROUTE_V3.TREATMENT_EVOLVE,
                    INTAKE_ROUTE_V3.TREATMENT_SUPPORT,
                    INTAKE_ROUTE_V3.TREATMENT_SAFETY,
                    INTAKE_ROUTE_V3.WEIGHT_LOSS_DATA_PROCESSING,
                    INTAKE_ROUTE_V3.ORDER_SUMMARY_V4,
                    INTAKE_ROUTE_V3.WL_FEMALE_SAFETY,
                    INTAKE_ROUTE_V3.WL_GOOD_HANDS_REVIEW,
                    INTAKE_ROUTE_V3.WHATS_NEXT,
                    INTAKE_ROUTE_V3.SHIPPING_INFORMATION,
                    INTAKE_ROUTE_V3.SECURITY_DISCLAIMER,
                    INTAKE_ROUTE_V3.ID_VERIFICATION,
                    INTAKE_ROUTE_V3.WL_CHECKOUT_HERS,
                ],
            },
            // {
            //     name: 'V3 Global WL Funnel Zealthy Best Practices',
            //     id: AB_TESTS_IDS.ZEALTHY_BEST_PRACTICES,
            //     version: 1,
            //     route_array: [
            //         INTAKE_ROUTE.WEIGHT_LOSS_INTRO_1,
            //         INTAKE_ROUTE_V3.WEIGHT_LOSS_INTRO_2,
            //         INTAKE_ROUTE_V3.REASONS_TO_BELIEVE,
            //         INTAKE_ROUTE_V3.WL_INTRO_SPECIALISTS,
            //         INTAKE_ROUTE_V3.REGISTRATION,
            //         INTAKE_ROUTE_V3.STATE_SELECTION,
            //         INTAKE_ROUTE_V3.DATE_OF_BIRTH,
            //         INTAKE_ROUTE_V3.GOOD_NEWS,
            //         INTAKE_ROUTE_V3.WEIGHT_LOSS_DEMOGRAPHICS,
            //         INTAKE_ROUTE_V3.GREETING,
            //         INTAKE_ROUTE_V3.UP_NEXT,
            //         INTAKE_ROUTE_V3.QUESTIONS,
            //         INTAKE_ROUTE_V3.PATIENT_MATCH,
            //         INTAKE_ROUTE_V3.WEIGHT_LOSS_GRAPH,
            //         INTAKE_ROUTE_V3.WEIGHT_LOSS_INTRO_3,
            //         INTAKE_ROUTE_V3.WEIGHT_LOSS_SUPPLY,
            //         INTAKE_ROUTE_V3.ORDER_SUMMARY_ZBP,
            //         INTAKE_ROUTE_V3.WEIGHT_LOSS_REVIEWS_ZBP,
            //         INTAKE_ROUTE_V3.SHIPPING_INFORMATION,
            //         INTAKE_ROUTE_V3.WEIGHT_LOSS_CHECKOUT_V3_ZBP,
            //         INTAKE_ROUTE_V3.PRE_ID_VERIFICATION,
            //         INTAKE_ROUTE_V3.ID_VERIFICATION,
            //     ],
            // },
        ],
    },
};

export const TIRZEPATIDE_ROUTES: IntakeRouteSpecification = {
    1: {
        version: 1,
        route_array: [
            INTAKE_ROUTE_V3.WEIGHT_LOSS_ACCOMPLISH_GOALS,
            INTAKE_ROUTE_V3.WEIGHT_LOSS_BMI,
            INTAKE_ROUTE_V3.WEIGHT_LOSS_DATA_PROCESSING,
            INTAKE_ROUTE_V3.WEIGHT_LOSS_GRAPH_PRE_SIGNUP,
            INTAKE_ROUTE_V3.REASONS_TO_BELIEVE,
            INTAKE_ROUTE_V3.WL_INTRO_SPECIALISTS,
            INTAKE_ROUTE_V3.STATE_SELECTION,
            INTAKE_ROUTE_V3.DATE_OF_BIRTH,
            INTAKE_ROUTE_V3.GOOD_NEWS,
            INTAKE_ROUTE_V3.WEIGHT_LOSS_DEMOGRAPHICS,
            INTAKE_ROUTE_V3.GREETING,
            INTAKE_ROUTE_V3.UP_NEXT_V3_WL,
            INTAKE_ROUTE_V3.QUESTIONS,
            INTAKE_ROUTE_V3.WEIGHT_LOSS_INTRO_3,
            INTAKE_ROUTE_V3.WEIGHT_LOSS_SUPPLY,
            INTAKE_ROUTE_V3.ORDER_SUMMARY,
            INTAKE_ROUTE_V3.WEIGHT_LOSS_REVIEWS,
            INTAKE_ROUTE_V3.PRE_ID_VERIFICATION,
            INTAKE_ROUTE_V3.ID_VERIFICATION,
            INTAKE_ROUTE_V3.SHIPPING_INFORMATION,
            INTAKE_ROUTE_V3.WEIGHT_LOSS_CHECKOUT,
        ],
        ab_tests: [
            {
                name: 'WL Funnel No 6 Month Option',
                id: AB_TESTS_IDS.WL_FUNNEL_NO_6,
                version: 1,
                route_array: [
                    INTAKE_ROUTE.WEIGHT_LOSS_INTRO_1,
                    INTAKE_ROUTE_V3.WEIGHT_LOSS_INTRO_2,
                    INTAKE_ROUTE_V3.REASONS_TO_BELIEVE,
                    INTAKE_ROUTE_V3.WL_INTRO_SPECIALISTS,
                    INTAKE_ROUTE_V3.REGISTRATION,
                    INTAKE_ROUTE_V3.STATE_SELECTION,
                    INTAKE_ROUTE_V3.DATE_OF_BIRTH,
                    INTAKE_ROUTE_V3.GOOD_NEWS,
                    INTAKE_ROUTE_V3.WEIGHT_LOSS_DEMOGRAPHICS,
                    INTAKE_ROUTE_V3.GREETING,
                    INTAKE_ROUTE_V3.UP_NEXT,
                    INTAKE_ROUTE_V3.QUESTIONS,
                    INTAKE_ROUTE_V3.PATIENT_MATCH,
                    INTAKE_ROUTE_V3.WEIGHT_LOSS_GRAPH,
                    INTAKE_ROUTE_V3.WEIGHT_LOSS_INTRO_3,
                    INTAKE_ROUTE_V3.WEIGHT_LOSS_SUPPLY_NO_6,
                    INTAKE_ROUTE_V3.ORDER_SUMMARY,
                    INTAKE_ROUTE_V3.WEIGHT_LOSS_REVIEWS,
                    INTAKE_ROUTE_V3.PRE_ID_VERIFICATION,
                    INTAKE_ROUTE_V3.ID_VERIFICATION,
                    INTAKE_ROUTE_V3.SHIPPING_INFORMATION,
                    INTAKE_ROUTE_V3.WEIGHT_LOSS_CHECKOUT,
                ],
            },
            // {
            //     name: 'WL Funnel Show ID After Checkout',
            //     id: AB_TESTS_IDS.WL_SHOW_ID_AFTER_CHECKOUT,
            //     version: 1,
            //     route_array: [
            //         INTAKE_ROUTE.WEIGHT_LOSS_INTRO_1,
            //         INTAKE_ROUTE_V3.WEIGHT_LOSS_INTRO_2,
            //         INTAKE_ROUTE_V3.REASONS_TO_BELIEVE,
            //         INTAKE_ROUTE_V3.WL_INTRO_SPECIALISTS,
            //         INTAKE_ROUTE_V3.REGISTRATION,
            //         INTAKE_ROUTE_V3.STATE_SELECTION,
            //         INTAKE_ROUTE_V3.DATE_OF_BIRTH,
            //         INTAKE_ROUTE_V3.GOOD_NEWS,
            //         INTAKE_ROUTE_V3.WEIGHT_LOSS_DEMOGRAPHICS,
            //         INTAKE_ROUTE_V3.GREETING,
            //         INTAKE_ROUTE_V3.UP_NEXT,
            //         INTAKE_ROUTE_V3.QUESTIONS,
            //         INTAKE_ROUTE_V3.PATIENT_MATCH,
            //         INTAKE_ROUTE_V3.WEIGHT_LOSS_GRAPH,
            //         INTAKE_ROUTE_V3.WEIGHT_LOSS_INTRO_3,
            //         INTAKE_ROUTE_V3.WEIGHT_LOSS_SUPPLY,
            //         INTAKE_ROUTE_V3.ORDER_SUMMARY,
            //         INTAKE_ROUTE_V3.WEIGHT_LOSS_REVIEWS,
            //         INTAKE_ROUTE_V3.SHIPPING_INFORMATION,
            //         INTAKE_ROUTE_V3.WEIGHT_LOSS_CHECKOUT,
            //         INTAKE_ROUTE_V3.PRE_ID_POST_CO,
            //         INTAKE_ROUTE_V3.ID_VERIFICATION_POST_CO,
            //     ],
            // },
            {
                name: 'WL Funnel Show Graph First Flow',
                id: AB_TESTS_IDS.WL_SHOW_GRAPH_FIRST,
                version: 1,
                route_array: [
                    INTAKE_ROUTE_V3.WEIGHT_LOSS_ACCOMPLISH_GOALS,
                    INTAKE_ROUTE_V3.WEIGHT_LOSS_BMI,
                    INTAKE_ROUTE_V3.WEIGHT_LOSS_DATA_PROCESSING,
                    INTAKE_ROUTE_V3.WEIGHT_LOSS_GRAPH_PRE_SIGNUP,
                    INTAKE_ROUTE_V3.REASONS_TO_BELIEVE,
                    INTAKE_ROUTE_V3.WL_INTRO_SPECIALISTS,
                    INTAKE_ROUTE_V3.STATE_SELECTION,
                    INTAKE_ROUTE_V3.DATE_OF_BIRTH,
                    INTAKE_ROUTE_V3.GOOD_NEWS,
                    INTAKE_ROUTE_V3.WEIGHT_LOSS_DEMOGRAPHICS,
                    INTAKE_ROUTE_V3.GREETING,
                    INTAKE_ROUTE_V3.UP_NEXT,
                    INTAKE_ROUTE_V3.QUESTIONS,
                    INTAKE_ROUTE_V3.WEIGHT_LOSS_INTRO_3,
                    INTAKE_ROUTE_V3.WEIGHT_LOSS_SUPPLY,
                    INTAKE_ROUTE_V3.ORDER_SUMMARY,
                    INTAKE_ROUTE_V3.WEIGHT_LOSS_REVIEWS,
                    INTAKE_ROUTE_V3.SHIPPING_INFORMATION,
                    INTAKE_ROUTE_V3.WEIGHT_LOSS_CHECKOUT,
                    INTAKE_ROUTE_V3.PRE_ID_POST_CO,
                    INTAKE_ROUTE_V3.ID_VERIFICATION_POST_CO,
                ],
            },
        ],
    },
};
//
/**
 * Deprecated below.
 */
export const WL_INTAKE_ROUTES: IntakeRouteSpecification = {
    1: {
        version: 1,
        route_array: [
            INTAKE_ROUTE.WEIGHT_LOSS_INTRO_1,
            INTAKE_ROUTE.WEIGHT_LOSS_INTRO_2,
            INTAKE_ROUTE.REGISTRATION,
            INTAKE_ROUTE.STATE_SELECTION,
            INTAKE_ROUTE.DATE_OF_BIRTH,
            INTAKE_ROUTE.DEMOGRAPHIC_INFORMATION,
            INTAKE_ROUTE.GOOD_TO_GO,
            INTAKE_ROUTE.QUESTIONS,
            INTAKE_ROUTE.PATIENT_MATCH,
            INTAKE_ROUTE.WEIGHT_LOSS_GRAPH,
            INTAKE_ROUTE.REASONS_TO_BELIEVE,
            INTAKE_ROUTE.PRODUCT_OVERVIEW,
            INTAKE_ROUTE.PRE_ID_VERIFICATION,
            INTAKE_ROUTE.ID_VERIFICATION,
            INTAKE_ROUTE.SHIPPING_INFORMATION,
            INTAKE_ROUTE.CHECKOUT,
        ],
        ab_tests: [],
    },
    2: {
        version: 2,
        route_array: [
            INTAKE_ROUTE.WEIGHT_LOSS_INTRO_1,
            INTAKE_ROUTE.WEIGHT_LOSS_INTRO_2,
            INTAKE_ROUTE.REASONS_TO_BELIEVE,
            INTAKE_ROUTE.REGISTRATION,
            INTAKE_ROUTE.STATE_SELECTION,
            INTAKE_ROUTE.DATE_OF_BIRTH,
            INTAKE_ROUTE.WEIGHT_LOSS_DEMOGRAPHICS,
            INTAKE_ROUTE.GREETING,
            INTAKE_ROUTE.UP_NEXT,
            INTAKE_ROUTE.QUESTIONS,
            INTAKE_ROUTE.PATIENT_MATCH,
            INTAKE_ROUTE.WEIGHT_LOSS_GRAPH,
            INTAKE_ROUTE.WEIGHT_LOSS_INTRO_3,
            INTAKE_ROUTE.WEIGHT_LOSS_SUPPLY,
            INTAKE_ROUTE.ORDER_SUMMARY,
            INTAKE_ROUTE.PRE_ID_VERIFICATION,
            INTAKE_ROUTE.ID_VERIFICATION,
            INTAKE_ROUTE.SHIPPING_INFORMATION,
            INTAKE_ROUTE.WEIGHT_LOSS_CHECKOUT,
        ],
        ab_tests: [],
    },
    3: {
        version: 3,
        ab_tests: [
            {
                name: 'WL Funnel With Transition Screens',
                id: AB_TESTS_IDS.WL_FUNNEL_W_TRANSITIONS,
                version: 1,
                route_array: [
                    INTAKE_ROUTE.WEIGHT_LOSS_INTRO_1,
                    INTAKE_ROUTE.WEIGHT_LOSS_INTRO_2,
                    INTAKE_ROUTE.REASONS_TO_BELIEVE,
                    INTAKE_ROUTE.REGISTRATION,
                    INTAKE_ROUTE.STATE_SELECTION,
                    INTAKE_ROUTE.DATE_OF_BIRTH,
                    INTAKE_ROUTE.WEIGHT_LOSS_DEMOGRAPHICS,
                    INTAKE_ROUTE.GREETING,
                    INTAKE_ROUTE.UP_NEXT,
                    INTAKE_ROUTE.QUESTIONS,
                    INTAKE_ROUTE.PATIENT_MATCH,
                    INTAKE_ROUTE.WEIGHT_LOSS_GRAPH,
                    INTAKE_ROUTE.WEIGHT_LOSS_INTRO_3,
                    INTAKE_ROUTE.WEIGHT_LOSS_SUPPLY,
                    INTAKE_ROUTE.ORDER_SUMMARY,
                    INTAKE_ROUTE.PRE_ID_VERIFICATION,
                    INTAKE_ROUTE.ID_VERIFICATION,
                    INTAKE_ROUTE.SHIPPING_INFORMATION,
                    INTAKE_ROUTE.WEIGHT_LOSS_CHECKOUT,
                ],
            },
            {
                name: 'WL Funnel New Design V3',
                id: AB_TESTS_IDS.WL_FUNNEL_V3,
                version: 1,
                route_array: [
                    INTAKE_ROUTE_V3.WEIGHT_LOSS_INTRO_1,
                    INTAKE_ROUTE_V3.WEIGHT_LOSS_INTRO_2,
                    INTAKE_ROUTE_V3.REASONS_TO_BELIEVE,
                    INTAKE_ROUTE_V3.WL_INTRO_SPECIALISTS,
                    INTAKE_ROUTE_V3.REGISTRATION,
                    INTAKE_ROUTE_V3.STATE_SELECTION,
                    INTAKE_ROUTE_V3.DATE_OF_BIRTH,
                    INTAKE_ROUTE_V3.GOOD_NEWS,
                    INTAKE_ROUTE_V3.WEIGHT_LOSS_DEMOGRAPHICS,
                    INTAKE_ROUTE_V3.GREETING,
                    INTAKE_ROUTE_V3.UP_NEXT,
                    INTAKE_ROUTE_V3.QUESTIONS,
                    INTAKE_ROUTE_V3.PATIENT_MATCH,
                    INTAKE_ROUTE_V3.WEIGHT_LOSS_GRAPH,
                    INTAKE_ROUTE_V3.WEIGHT_LOSS_INTRO_3,
                    INTAKE_ROUTE_V3.WEIGHT_LOSS_SUPPLY,
                    INTAKE_ROUTE_V3.ORDER_SUMMARY,
                    INTAKE_ROUTE_V3.WEIGHT_LOSS_REVIEWS,
                    INTAKE_ROUTE_V3.PRE_ID_VERIFICATION,
                    INTAKE_ROUTE_V3.ID_VERIFICATION,
                    INTAKE_ROUTE_V3.SHIPPING_INFORMATION,
                    INTAKE_ROUTE_V3.WEIGHT_LOSS_CHECKOUT,
                    INTAKE_ROUTE_V3.WEIGHT_LOSS_DATA_PROCESSING,
                ],
            },
        ],
        route_array: [
            INTAKE_ROUTE.WEIGHT_LOSS_INTRO_1,
            INTAKE_ROUTE.WEIGHT_LOSS_INTRO_2,
            INTAKE_ROUTE.REASONS_TO_BELIEVE,
            INTAKE_ROUTE.REGISTRATION,
            INTAKE_ROUTE.STATE_SELECTION,
            INTAKE_ROUTE.DATE_OF_BIRTH,
            INTAKE_ROUTE.WEIGHT_LOSS_DEMOGRAPHICS,
            INTAKE_ROUTE.GREETING,
            INTAKE_ROUTE.UP_NEXT,
            INTAKE_ROUTE.QUESTIONS,
            INTAKE_ROUTE.PATIENT_MATCH,
            INTAKE_ROUTE.WEIGHT_LOSS_GRAPH,
            INTAKE_ROUTE.WEIGHT_LOSS_INTRO_3,
            INTAKE_ROUTE.WEIGHT_LOSS_SUPPLY,
            INTAKE_ROUTE.ORDER_SUMMARY,
            INTAKE_ROUTE.PRE_ID_VERIFICATION,
            INTAKE_ROUTE.ID_VERIFICATION,
            INTAKE_ROUTE.SHIPPING_INFORMATION,
            INTAKE_ROUTE.WEIGHT_LOSS_CHECKOUT,
        ],
    },
};

export const NAD_INTAKE_ROUTES: IntakeRouteSpecification = {
    1: {
        version: 1,
        route_array: [
            INTAKE_ROUTE.IMPROVE_HEALTH,
            INTAKE_ROUTE.ON_YOUR_WAY,
            INTAKE_ROUTE.FATIGUE_STAT,
            INTAKE_ROUTE.NAD_BENEFITS,
            INTAKE_ROUTE.REGISTRATION,
            INTAKE_ROUTE.STATE_SELECTION,
            INTAKE_ROUTE.DATE_OF_BIRTH,
            INTAKE_ROUTE.WEIGHT_LOSS_DEMOGRAPHICS,
            INTAKE_ROUTE.GREETING,
            INTAKE_ROUTE.UP_NEXT_HEALTH,
            INTAKE_ROUTE.QUESTIONS,
            INTAKE_ROUTE.UP_NEXT_ID,
            INTAKE_ROUTE.ID_VERIFICATION,
            INTAKE_ROUTE.PATIENT_MATCH,
            INTAKE_ROUTE.UP_NEXT_PREVIEW,
            INTAKE_ROUTE.PRODUCT_OVERVIEW,
            INTAKE_ROUTE.SHIPPING_INFORMATION,
            INTAKE_ROUTE.CHECKOUT,
        ],
        ab_tests: [],
    },
    2: {
        version: 2,
        route_array: [
            INTAKE_ROUTE_V3.IMPROVE_HEALTH_AP,
            INTAKE_ROUTE_V3.ON_YOUR_WAY,
            INTAKE_ROUTE_V3.FATIGUE_STAT_V3,
            INTAKE_ROUTE_V3.NAD_BENEFITS_V3,
            INTAKE_ROUTE_V3.REGISTRATION,
            INTAKE_ROUTE_V3.STATE_SELECTION,
            INTAKE_ROUTE_V3.DATE_OF_BIRTH,
            INTAKE_ROUTE_V3.DEMOGRAPHIC_COLLECTION, //INTAKE_ROUTE_V3.DEMOGRAPHIC_COLLECTION
            INTAKE_ROUTE_V3.GREETING,
            INTAKE_ROUTE_V3.UP_NEXT_HEALTH_V3_AP,
            INTAKE_ROUTE_V3.QUESTIONS,
            INTAKE_ROUTE_V3.UP_NEXT_ID_V3_AP,
            INTAKE_ROUTE_V3.ID_VERIFICATION,
            INTAKE_ROUTE_V3.SHIPPING_INFORMATION,
            INTAKE_ROUTE_V3.UP_NEXT_PREVIEW_V3_AP,
            INTAKE_ROUTE_V3.ORDER_SUMMARY_V3_AP,
            INTAKE_ROUTE_V3.ONE_MOMENT,
            INTAKE_ROUTE_V3.NEW_NON_WL_CHECKOUT,
        ],
        ab_tests: [],
    },
};

export const COMBINED_WEIGHT_LOSS_ROUTES: IntakeRouteSpecification = {
    1: {
        version: 1,
        route_array: [
            INTAKE_ROUTE.WEIGHT_LOSS_INTRO_SCREEN,
            INTAKE_ROUTE.WEIGHT_LOSS_INTRO_OPTIONS,
            INTAKE_ROUTE.WEIGHT_LOSS_INTRO_1,
            INTAKE_ROUTE.WEIGHT_LOSS_INTRO_GRAPH,
            INTAKE_ROUTE.WEIGHT_LOSS_INTRO_SPECIALISTS,
            INTAKE_ROUTE.REASONS_TO_BELIEVE,
            INTAKE_ROUTE.START_WEIGHT_LOSS_JOURNEY,
            INTAKE_ROUTE.WEIGHT_LOSS_INTRO_QUESTION_1,
            INTAKE_ROUTE.WEIGHT_LOSS_INTRO_QUESTION_2,
            INTAKE_ROUTE.WEIGHT_LOSS_INFORM_1,
            INTAKE_ROUTE.WEIGHT_LOSS_INTRO_QUESTION_3,
            INTAKE_ROUTE.WEIGHT_LOSS_INFORM_2,
            INTAKE_ROUTE.WEIGHT_LOSS_INTRO_QUESTION_4,
            INTAKE_ROUTE.WEIGHT_LOSS_INFORM_3,
            INTAKE_ROUTE.WEIGHT_LOSS_STAT,
            INTAKE_ROUTE.REGISTRATION,
            INTAKE_ROUTE.STATE_SELECTION,
            INTAKE_ROUTE.DATE_OF_BIRTH,
            INTAKE_ROUTE.PRE_DEMOGRAPHIC,
            INTAKE_ROUTE.COMBINED_WEIGHT_LOSS_DEMOGRAPHIC,
            INTAKE_ROUTE.GREETING,
            INTAKE_ROUTE.WEIGHT_LOSS_UP_NEXT_PROFILE,
            INTAKE_ROUTE.QUESTIONS,
            INTAKE_ROUTE.WEIGHT_LOSS_CALCULATING,
            INTAKE_ROUTE.WEIGHT_LOSS_GRAPH,
            INTAKE_ROUTE.WEIGHT_LOSS_IN_GOOD_HANDS,
            // INTAKE_ROUTE.WEIGHT_LOSS_INTRO_3,
            INTAKE_ROUTE.WEIGHT_LOSS_SUPPLY_V2,
            INTAKE_ROUTE.ORDER_SUMMARY,
            INTAKE_ROUTE.WEIGHT_LOSS_REVIEWS,
            INTAKE_ROUTE.WEIGHT_LOSS_UP_NEXT_PREVIEW,
            INTAKE_ROUTE.ID_VERIFICATION,
            INTAKE_ROUTE.SHIPPING_INFORMATION,
            INTAKE_ROUTE.WEIGHT_LOSS_CHECKOUT_V2,
        ],
        ab_tests: [],
    },
    2: {
        version: 2,
        ab_tests: [
            {
                name: 'WL Funnel w/o Transitions',
                id: AB_TESTS_IDS.WL_FUNNEL_WO_TRANSITIONS,
                version: 1,
                route_array: [
                    INTAKE_ROUTE.WEIGHT_LOSS_INTRO_1,
                    INTAKE_ROUTE.REGISTRATION,
                    INTAKE_ROUTE.STATE_SELECTION,
                    INTAKE_ROUTE.DATE_OF_BIRTH,
                    INTAKE_ROUTE.PRE_DEMOGRAPHIC,
                    INTAKE_ROUTE.COMBINED_WEIGHT_LOSS_DEMOGRAPHIC,
                    INTAKE_ROUTE.WEIGHT_LOSS_UP_NEXT_PROFILE,
                    INTAKE_ROUTE.QUESTIONS,
                    INTAKE_ROUTE.WEIGHT_LOSS_IN_GOOD_HANDS,
                    // INTAKE_ROUTE.WEIGHT_LOSS_INTRO_3,
                    INTAKE_ROUTE.WEIGHT_LOSS_SUPPLY_V2,
                    INTAKE_ROUTE.ORDER_SUMMARY,
                    INTAKE_ROUTE.WEIGHT_LOSS_REVIEWS,
                    INTAKE_ROUTE.WEIGHT_LOSS_UP_NEXT_PREVIEW,
                    INTAKE_ROUTE.ID_VERIFICATION,
                    INTAKE_ROUTE.SHIPPING_INFORMATION,
                    INTAKE_ROUTE.WEIGHT_LOSS_CHECKOUT_V2,
                ],
            },
            {
                name: 'V3 Design Global WL Funnel',
                id: AB_TESTS_IDS.WL_FUNNEL_V3,
                version: 1,
                route_array: [
                    INTAKE_ROUTE_V3.WEIGHT_LOSS_INTRO_OPTIONS_V3,
                    INTAKE_ROUTE_V3.WEIGHT_LOSS_INTRO_1,
                    INTAKE_ROUTE_V3.WEIGHT_LOSS_INTRO_GRAPH_V3,
                    INTAKE_ROUTE_V3.WL_INTRO_SPECIALISTS,
                    INTAKE_ROUTE_V3.REASONS_TO_BELIEVE,
                    INTAKE_ROUTE_V3.START_WEIGHT_LOSS_JOURNEY_V3,
                    INTAKE_ROUTE_V3.WEIGHT_LOSS_INTRO_QUESTION_1_V3,
                    INTAKE_ROUTE_V3.WEIGHT_LOSS_INTRO_QUESTION_2_V3,
                    INTAKE_ROUTE_V3.WEIGHT_LOSS_INFORM_1_V3,
                    INTAKE_ROUTE_V3.WEIGHT_LOSS_INTRO_QUESTION_3_V3,
                    INTAKE_ROUTE_V3.WEIGHT_LOSS_INFORM_2_V3,
                    INTAKE_ROUTE_V3.WEIGHT_LOSS_INTRO_QUESTION_4_V3,
                    INTAKE_ROUTE_V3.WEIGHT_LOSS_INFORM_3_V3,
                    INTAKE_ROUTE_V3.WEIGHT_LOSS_STAT_V3,
                    INTAKE_ROUTE_V3.REGISTRATION,
                    INTAKE_ROUTE_V3.STATE_SELECTION,
                    INTAKE_ROUTE_V3.DATE_OF_BIRTH,
                    INTAKE_ROUTE_V3.GOOD_NEWS,
                    INTAKE_ROUTE_V3.WEIGHT_LOSS_DEMOGRAPHICS,
                    INTAKE_ROUTE_V3.GREETING,
                    INTAKE_ROUTE_V3.UP_NEXT,
                    INTAKE_ROUTE_V3.QUESTIONS,
                    INTAKE_ROUTE_V3.WEIGHT_LOSS_CALCULATING_V3,
                    INTAKE_ROUTE_V3.WEIGHT_LOSS_GRAPH,
                    INTAKE_ROUTE_V3.WEIGHT_LOSS_INTRO_3,
                    INTAKE_ROUTE_V3.WEIGHT_LOSS_SUPPLY,
                    INTAKE_ROUTE_V3.ORDER_SUMMARY,
                    INTAKE_ROUTE_V3.WEIGHT_LOSS_REVIEWS,
                    INTAKE_ROUTE_V3.PRE_ID_VERIFICATION,
                    INTAKE_ROUTE_V3.ID_VERIFICATION,
                    INTAKE_ROUTE_V3.SHIPPING_INFORMATION,
                    INTAKE_ROUTE_V3.WEIGHT_LOSS_CHECKOUT,
                ],
            },
            // {
            //     name: 'V3 Global WL Funnel ID after Checkout',
            //     id: AB_TESTS_IDS.WL_GLOBAL_SHOW_ID_AFTER_CHECKOUT,
            //     version: 1,
            //     route_array: [
            //         INTAKE_ROUTE_V3.WEIGHT_LOSS_INTRO_OPTIONS_V3,
            //         INTAKE_ROUTE_V3.WEIGHT_LOSS_INTRO_1,
            //         INTAKE_ROUTE_V3.WEIGHT_LOSS_INTRO_GRAPH_V3,
            //         INTAKE_ROUTE_V3.WL_INTRO_SPECIALISTS,
            //         INTAKE_ROUTE_V3.REASONS_TO_BELIEVE,
            //         INTAKE_ROUTE_V3.START_WEIGHT_LOSS_JOURNEY_V3,
            //         INTAKE_ROUTE_V3.WEIGHT_LOSS_INTRO_QUESTION_1_V3,
            //         INTAKE_ROUTE_V3.WEIGHT_LOSS_INTRO_QUESTION_2_V3,
            //         INTAKE_ROUTE_V3.WEIGHT_LOSS_INFORM_1_V3,
            //         INTAKE_ROUTE_V3.WEIGHT_LOSS_INTRO_QUESTION_3_V3,
            //         INTAKE_ROUTE_V3.WEIGHT_LOSS_INFORM_2_V3,
            //         INTAKE_ROUTE_V3.WEIGHT_LOSS_INTRO_QUESTION_4_V3,
            //         INTAKE_ROUTE_V3.WEIGHT_LOSS_INFORM_3_V3,
            //         INTAKE_ROUTE_V3.WEIGHT_LOSS_STAT_V3,
            //         INTAKE_ROUTE_V3.REGISTRATION,
            //         INTAKE_ROUTE_V3.STATE_SELECTION,
            //         INTAKE_ROUTE_V3.DATE_OF_BIRTH,
            //         INTAKE_ROUTE_V3.GOOD_NEWS,
            //         INTAKE_ROUTE_V3.WEIGHT_LOSS_DEMOGRAPHICS,
            //         INTAKE_ROUTE_V3.GREETING,
            //         INTAKE_ROUTE_V3.UP_NEXT,
            //         INTAKE_ROUTE_V3.QUESTIONS,
            //         INTAKE_ROUTE_V3.WEIGHT_LOSS_CALCULATING_V3,
            //         INTAKE_ROUTE_V3.WEIGHT_LOSS_GRAPH,
            //         INTAKE_ROUTE_V3.WEIGHT_LOSS_INTRO_3,
            //         INTAKE_ROUTE_V3.WEIGHT_LOSS_SUPPLY,
            //         INTAKE_ROUTE_V3.ORDER_SUMMARY,
            //         INTAKE_ROUTE_V3.WEIGHT_LOSS_REVIEWS,
            //         INTAKE_ROUTE_V3.SHIPPING_INFORMATION,
            //         INTAKE_ROUTE_V3.WEIGHT_LOSS_CHECKOUT,
            //         INTAKE_ROUTE_V3.PRE_ID_POST_CO,
            //         INTAKE_ROUTE_V3.ID_VERIFICATION_POST_CO,
            //     ],
            // },
            // {
            //     name: 'V3 Global WL Funnel Zealthy Best Practices',
            //     id: AB_TESTS_IDS.ZEALTHY_BEST_PRACTICES,
            //     version: 1,
            //     route_array: [
            //         INTAKE_ROUTE_V3.WEIGHT_LOSS_INTRO_OPTIONS_V3,
            //         INTAKE_ROUTE_V3.WEIGHT_LOSS_INTRO_1,
            //         INTAKE_ROUTE_V3.WEIGHT_LOSS_INTRO_GRAPH_V3,
            //         INTAKE_ROUTE_V3.WL_INTRO_SPECIALISTS,
            //         INTAKE_ROUTE_V3.REASONS_TO_BELIEVE,
            //         INTAKE_ROUTE_V3.START_WEIGHT_LOSS_JOURNEY_V3,
            //         INTAKE_ROUTE_V3.WEIGHT_LOSS_INTRO_QUESTION_1_V3,
            //         INTAKE_ROUTE_V3.WEIGHT_LOSS_INTRO_QUESTION_2_V3,
            //         INTAKE_ROUTE_V3.WEIGHT_LOSS_INFORM_1_V3,
            //         INTAKE_ROUTE_V3.WEIGHT_LOSS_INTRO_QUESTION_3_V3,
            //         INTAKE_ROUTE_V3.WEIGHT_LOSS_INFORM_2_V3,
            //         INTAKE_ROUTE_V3.WEIGHT_LOSS_INTRO_QUESTION_4_V3,
            //         INTAKE_ROUTE_V3.WEIGHT_LOSS_INFORM_3_V3,
            //         INTAKE_ROUTE_V3.WEIGHT_LOSS_STAT_V3,
            //         INTAKE_ROUTE_V3.REGISTRATION,
            //         INTAKE_ROUTE_V3.STATE_SELECTION,
            //         INTAKE_ROUTE_V3.DATE_OF_BIRTH,
            //         INTAKE_ROUTE_V3.GOOD_NEWS,
            //         INTAKE_ROUTE_V3.WEIGHT_LOSS_DEMOGRAPHICS,
            //         INTAKE_ROUTE_V3.GREETING,
            //         INTAKE_ROUTE_V3.UP_NEXT,
            //         INTAKE_ROUTE_V3.QUESTIONS,
            //         INTAKE_ROUTE_V3.WEIGHT_LOSS_DATA_PROCESSING,
            //         INTAKE_ROUTE_V3.WEIGHT_LOSS_GRAPH,
            //         INTAKE_ROUTE_V3.WEIGHT_LOSS_INTRO_3,
            //         INTAKE_ROUTE_V3.WEIGHT_LOSS_SUPPLY,
            //         INTAKE_ROUTE_V3.ORDER_SUMMARY_ZBP, //we use this route so it doesn't trigger Olivier's vwo test 7
            //         INTAKE_ROUTE_V3.SHIPPING_INFORMATION,
            //         INTAKE_ROUTE_V3.WEIGHT_LOSS_CHECKOUT_V3_ZBP,
            //         INTAKE_ROUTE_V3.PRE_ID_VERIFICATION,
            //         INTAKE_ROUTE_V3.ID_VERIFICATION,
            //     ],
            // },
            {
                name: 'WL Funnel RO TEST',
                id: AB_TESTS_IDS.WL_RO_TEST,
                version: 1,
                route_array: [
                    INTAKE_ROUTE_V3.WEIGHT_LOSS_ACCOMPLISH_GOALS,
                    INTAKE_ROUTE_V3.WEIGHT_LOSS_BMI,
                    INTAKE_ROUTE_V3.WEIGHT_LOSS_DATA_PROCESSING,
                    INTAKE_ROUTE_V3.WEIGHT_LOSS_GRAPH_PRE_SIGNUP,
                    INTAKE_ROUTE_V3.WL_INTRO_SPECIALISTS,
                    INTAKE_ROUTE_V3.REASONS_TO_BELIEVE,
                    INTAKE_ROUTE_V3.START_WEIGHT_LOSS_JOURNEY_V3,
                    INTAKE_ROUTE_V3.WEIGHT_LOSS_INTRO_QUESTION_1_V3,
                    INTAKE_ROUTE_V3.WEIGHT_LOSS_INTRO_QUESTION_2_V3,
                    INTAKE_ROUTE_V3.WEIGHT_LOSS_INFORM_1_V3,
                    INTAKE_ROUTE_V3.WEIGHT_LOSS_INTRO_QUESTION_3_V3,
                    INTAKE_ROUTE_V3.WEIGHT_LOSS_INFORM_2_V3,
                    INTAKE_ROUTE_V3.WEIGHT_LOSS_INTRO_QUESTION_4_V3,
                    INTAKE_ROUTE_V3.WEIGHT_LOSS_INFORM_3_V3,
                    INTAKE_ROUTE_V3.WEIGHT_LOSS_STAT_V3,
                    INTAKE_ROUTE_V3.STATE_SELECTION,
                    INTAKE_ROUTE_V3.DATE_OF_BIRTH,
                    INTAKE_ROUTE_V3.GOOD_NEWS,
                    INTAKE_ROUTE_V3.WEIGHT_LOSS_DEMOGRAPHICS,
                    INTAKE_ROUTE_V3.GREETING,
                    INTAKE_ROUTE_V3.UP_NEXT_V3_WL,
                    INTAKE_ROUTE_V3.QUESTIONS,
                    INTAKE_ROUTE_V3.WEIGHT_LOSS_DATA_PROCESSING_2,
                    INTAKE_ROUTE_V3.WEIGHT_LOSS_INTRO_3,
                    INTAKE_ROUTE_V3.WEIGHT_LOSS_SUPPLY,
                    INTAKE_ROUTE_V3.ORDER_SUMMARY,
                    INTAKE_ROUTE_V3.WEIGHT_LOSS_REVIEWS,
                    INTAKE_ROUTE_V3.PRE_ID_VERIFICATION,
                    INTAKE_ROUTE_V3.ID_VERIFICATION,
                    INTAKE_ROUTE_V3.SHIPPING_INFORMATION,
                    INTAKE_ROUTE_V3.WEIGHT_LOSS_CHECKOUT,
                ],
            },
        ],

        route_array: [
            INTAKE_ROUTE_V3.WEIGHT_LOSS_INTRO_OPTIONS_V3,
            INTAKE_ROUTE_V3.WEIGHT_LOSS_INTRO_1,
            INTAKE_ROUTE_V3.WEIGHT_LOSS_INTRO_GRAPH_V3,
            INTAKE_ROUTE_V3.WL_INTRO_SPECIALISTS,
            INTAKE_ROUTE_V3.REASONS_TO_BELIEVE,
            INTAKE_ROUTE_V3.START_WEIGHT_LOSS_JOURNEY_V3,
            INTAKE_ROUTE_V3.WEIGHT_LOSS_INTRO_QUESTION_1_V3,
            INTAKE_ROUTE_V3.WEIGHT_LOSS_INTRO_QUESTION_2_V3,
            INTAKE_ROUTE_V3.WEIGHT_LOSS_INFORM_1_V3,
            INTAKE_ROUTE_V3.WEIGHT_LOSS_INTRO_QUESTION_3_V3,
            INTAKE_ROUTE_V3.WEIGHT_LOSS_INFORM_2_V3,
            INTAKE_ROUTE_V3.WEIGHT_LOSS_INTRO_QUESTION_4_V3,
            INTAKE_ROUTE_V3.WEIGHT_LOSS_INFORM_3_V3,
            INTAKE_ROUTE_V3.WEIGHT_LOSS_STAT_V3,
            INTAKE_ROUTE_V3.REGISTRATION,
            INTAKE_ROUTE_V3.STATE_SELECTION,
            INTAKE_ROUTE_V3.DATE_OF_BIRTH,
            INTAKE_ROUTE_V3.GOOD_NEWS,
            INTAKE_ROUTE_V3.WEIGHT_LOSS_DEMOGRAPHICS,
            INTAKE_ROUTE_V3.GREETING,
            INTAKE_ROUTE_V3.UP_NEXT_V3_WL,
            INTAKE_ROUTE_V3.QUESTIONS,
            INTAKE_ROUTE_V3.WEIGHT_LOSS_CALCULATING_V3,
            INTAKE_ROUTE_V3.WEIGHT_LOSS_GRAPH,
            INTAKE_ROUTE_V3.WEIGHT_LOSS_INTRO_3,
            INTAKE_ROUTE_V3.WEIGHT_LOSS_SUPPLY,
            INTAKE_ROUTE_V3.ORDER_SUMMARY,
            INTAKE_ROUTE_V3.WEIGHT_LOSS_REVIEWS,
            INTAKE_ROUTE_V3.PRE_ID_VERIFICATION,
            INTAKE_ROUTE_V3.ID_VERIFICATION,
            INTAKE_ROUTE_V3.SHIPPING_INFORMATION,
            INTAKE_ROUTE_V3.WEIGHT_LOSS_CHECKOUT,
        ],
    },
};

export const GLOBAL_WL_ROUTES: IntakeRouteSpecification = {
    1: {
        version: 1,
        route_array: [
            INTAKE_ROUTE_V3.GLOBAL_WL_INTRO,
            INTAKE_ROUTE_V3.GLOBAL_WL_GOAL_WEIGHT,
            INTAKE_ROUTE_V3.GLOBAL_WL_INTERACTIVE,
            INTAKE_ROUTE_V3.GLOBAL_WL_MEDICATIONS,
            INTAKE_ROUTE_V3.GLOBAL_WL_CHECKOUT,
            INTAKE_ROUTE_V3.GLOBAL_WL_UP_NEXT,
        ],
        ab_tests: [],
    },
};

export const SKINCARE_INTAKE_ROUTES: IntakeRouteSpecification = {
    1: {
        version: 1,
        route_array: [
            INTAKE_ROUTE.SKINCARE_INTRO,
            INTAKE_ROUTE.REGISTRATION,
            INTAKE_ROUTE.STATE_SELECTION,
            INTAKE_ROUTE.DATE_OF_BIRTH,
            INTAKE_ROUTE.WEIGHT_LOSS_DEMOGRAPHICS,
            INTAKE_ROUTE.GREETING,
            INTAKE_ROUTE.SKINCARE_UP_NEXT_HEALTH,
            INTAKE_ROUTE.QUESTIONS,
            INTAKE_ROUTE.SKINCARE_UP_NEXT_UPLOAD,
            INTAKE_ROUTE.ID_VERIFICATION,
            INTAKE_ROUTE.SKINCARE_UPLOAD,
            INTAKE_ROUTE.SKINCARE_FREQUENCY,
            INTAKE_ROUTE.PATIENT_MATCH,
            INTAKE_ROUTE.PRODUCT_OVERVIEW,
            INTAKE_ROUTE.SHIPPING_INFORMATION,
            INTAKE_ROUTE.NEW_CHECKOUT,
        ],
        ab_tests: [],
    },
    2: {
        version: 2,
        route_array: [
            INTAKE_ROUTE.SKINCARE_INTRO,
            INTAKE_ROUTE.SKINCARE_RESULTS,
            INTAKE_ROUTE.REGISTRATION,
            INTAKE_ROUTE.STATE_SELECTION,
            INTAKE_ROUTE.DATE_OF_BIRTH,
            INTAKE_ROUTE.SKINCARE_PRE_DEMOGRAPHIC,
            INTAKE_ROUTE.DEMOGRAPHIC_COLLECTION,
            INTAKE_ROUTE.GREETING,
            INTAKE_ROUTE.SKINCARE_UP_NEXT_HEALTH,
            INTAKE_ROUTE.QUESTIONS,
            INTAKE_ROUTE.SKINCARE_UP_NEXT_UPLOAD,
            INTAKE_ROUTE.ID_VERIFICATION,
            INTAKE_ROUTE.SKINCARE_UPLOAD,
            INTAKE_ROUTE.SKINCARE_SEE_OTHERS,
            INTAKE_ROUTE.SKINCARE_FREQUENCY,
            INTAKE_ROUTE.GENERAL_ORDER_SUMMARY,
            INTAKE_ROUTE.SHIPPING_INFORMATION,
            INTAKE_ROUTE.NEW_CHECKOUT,
        ],
        ab_tests: [],
    },
};

export const GLUTATHIONE_INTAKE_ROUTES: IntakeRouteSpecification = {
    1: {
        version: 1,
        route_array: [
            INTAKE_ROUTE.ENHANCE_ENERGY,
            INTAKE_ROUTE.GLUTATHIONE_ADVANTAGES,
            INTAKE_ROUTE.GLUTATHIONE_PROCESS,
            INTAKE_ROUTE.REGISTRATION,
            INTAKE_ROUTE.STATE_SELECTION,
            INTAKE_ROUTE.DATE_OF_BIRTH,
            INTAKE_ROUTE.PRE_DEMOGRAPHIC,
            INTAKE_ROUTE.DEMOGRAPHIC_COLLECTION,
            INTAKE_ROUTE.GREETING,
            INTAKE_ROUTE.UP_NEXT_3_HEALTH,
            INTAKE_ROUTE.QUESTIONS,
            INTAKE_ROUTE.PRE_ID_VERIFICATION,
            INTAKE_ROUTE.ID_VERIFICATION,
            INTAKE_ROUTE.GENERAL_ORDER_SUMMARY,
            INTAKE_ROUTE.WEIGHT_LOSS_IN_GOOD_HANDS,
            // INTAKE_ROUTE.PATIENT_MATCH,
            // INTAKE_ROUTE.UP_NEXT_PREVIEW,
            // INTAKE_ROUTE.PRODUCT_OVERVIEW,
            INTAKE_ROUTE.SHIPPING_INFORMATION,
            INTAKE_ROUTE.NEW_CHECKOUT,
        ],
        ab_tests: [],
    },
};

export const B12_INTAKE_ROUTES: IntakeRouteSpecification = {
    1: {
        version: 1,
        route_array: [
            INTAKE_ROUTE.IMPROVE_FUNCTION,
            INTAKE_ROUTE.B12_ADVANTAGES,
            INTAKE_ROUTE.REGISTRATION,
            INTAKE_ROUTE.STATE_SELECTION,
            INTAKE_ROUTE.DATE_OF_BIRTH,
            INTAKE_ROUTE.PRE_DEMOGRAPHIC,
            INTAKE_ROUTE.DEMOGRAPHIC_COLLECTION,
            INTAKE_ROUTE.GREETING,
            INTAKE_ROUTE.UP_NEXT_3_HEALTH,
            INTAKE_ROUTE.QUESTIONS,
            INTAKE_ROUTE.SELECT_SUPPLY,
            INTAKE_ROUTE.GENERAL_ORDER_SUMMARY,
            INTAKE_ROUTE.B12_REVIEWS,
            INTAKE_ROUTE.PRE_ID_VERIFICATION,
            INTAKE_ROUTE.ID_VERIFICATION,
            INTAKE_ROUTE.SHIPPING_INFORMATION,
            INTAKE_ROUTE.NEW_CHECKOUT,
        ],
        ab_tests: [],
    },
    2: {
        version: 2,
        route_array: [
            INTAKE_ROUTE_V3.IMPROVE_FUNCTION,
            INTAKE_ROUTE_V3.B12_ADVANTAGES,
            INTAKE_ROUTE_V3.REGISTRATION,
            INTAKE_ROUTE_V3.STATE_SELECTION,
            INTAKE_ROUTE_V3.DATE_OF_BIRTH,
            INTAKE_ROUTE_V3.GOOD_NEWS,
            INTAKE_ROUTE_V3.DEMOGRAPHIC_COLLECTION,
            INTAKE_ROUTE_V3.GREETING,
            INTAKE_ROUTE_V3.UP_NEXT,
            INTAKE_ROUTE_V3.QUESTIONS,
            INTAKE_ROUTE_V3.SELECT_SUPPLY,
            INTAKE_ROUTE_V3.GENERAL_ORDER_SUMMARY,
            INTAKE_ROUTE_V3.B12_REVIEWS,
            INTAKE_ROUTE_V3.PRE_ID_VERIFICATION,
            INTAKE_ROUTE_V3.ID_VERIFICATION,
            INTAKE_ROUTE_V3.SHIPPING_INFORMATION,
            INTAKE_ROUTE_V3.NEW_CHECKOUT,
        ],
        ab_tests: [],
    },
};

export const NAD_NASAL_SPRAY_INTAKE_ROUTES: IntakeRouteSpecification = {
    1: {
        version: 1,
        route_array: [
            INTAKE_ROUTE.IMPROVE_HEALTH,
            INTAKE_ROUTE.ON_YOUR_WAY,
            INTAKE_ROUTE.FATIGUE_STAT,
            INTAKE_ROUTE.NAD_BENEFITS,
            INTAKE_ROUTE.REGISTRATION,
            INTAKE_ROUTE.STATE_SELECTION,
            INTAKE_ROUTE.DATE_OF_BIRTH,
            INTAKE_ROUTE.DEMOGRAPHIC_COLLECTION,
            INTAKE_ROUTE.GREETING,
            INTAKE_ROUTE.UP_NEXT_4_HEALTH,
            INTAKE_ROUTE.QUESTIONS,
            INTAKE_ROUTE.PRE_ID_VERIFICATION_B,
            INTAKE_ROUTE.ID_VERIFICATION,
            INTAKE_ROUTE.PRODUCT_OVERVIEW,
            INTAKE_ROUTE.SHIPPING_INFORMATION,
            INTAKE_ROUTE.NEW_CHECKOUT,
        ],
        ab_tests: [],
    },
};

export const METFORMIN_INTAKE_ROUTES: IntakeRouteSpecification = {
    1: {
        version: 1,
        route_array: [
            INTAKE_ROUTE.WEIGHT_LOSS_INTRO_SCREEN,
            INTAKE_ROUTE.REASONS_TO_BELIEVE,
            INTAKE_ROUTE.REGISTRATION,
            INTAKE_ROUTE.STATE_SELECTION,
            INTAKE_ROUTE.DATE_OF_BIRTH,
            INTAKE_ROUTE.PRE_DEMOGRAPHIC,
            INTAKE_ROUTE.DEMOGRAPHIC_COLLECTION,
            INTAKE_ROUTE.GREETING,
            INTAKE_ROUTE.UP_NEXT_3_HEALTH,
            INTAKE_ROUTE.QUESTIONS,
            INTAKE_ROUTE.PATIENT_MATCH,
            INTAKE_ROUTE.WEIGHT_LOSS_UP_NEXT_PREVIEW,
            INTAKE_ROUTE.ID_VERIFICATION,
            INTAKE_ROUTE.GENERAL_ORDER_SUMMARY,
            INTAKE_ROUTE.SHIPPING_INFORMATION,
            INTAKE_ROUTE.NEW_CHECKOUT,
        ],
        ab_tests: [],
    },
};

export const VWO_TEST_QUESTIONNAIRES_VERSION_MAPPINGS: Partial<
    Record<PRODUCT_HREF, Partial<Record<AB_TESTS_IDS, number>>>
> = {
    [PRODUCT_HREF.SEMAGLUTIDE]: {
        [AB_TESTS_IDS.WL_HERS_FUNNEL]: 5,
    },
};

export const SERMORELIN_ROUTES: IntakeRouteSpecification = {
    1: {
        version: 1,
        route_array: [
            INTAKE_ROUTE_V3.REGISTRATION,
            INTAKE_ROUTE_V3.STATE_SELECTION_V3,
            INTAKE_ROUTE_V3.DATE_OF_BIRTH_V3,
            INTAKE_ROUTE_V3.GOOD_NEWS,
            INTAKE_ROUTE_V3.DEMOGRAPHIC_COLLECTION,
            INTAKE_ROUTE_V3.GREETING,
            INTAKE_ROUTE_V3.UP_NEXT_V3_AP,
            INTAKE_ROUTE_V3.QUESTIONS,
            INTAKE_ROUTE_V3.SELECT_SUPPLY_AP,
            INTAKE_ROUTE_V3.ORDER_SUMMARY_V3_AP,
            INTAKE_ROUTE_V3.PRE_ID_VERIFICATION_AP,
            INTAKE_ROUTE_V3.ID_VERIFICATION,
            INTAKE_ROUTE_V3.SHIPPING_INFORMATION,
            INTAKE_ROUTE_V3.NEW_CHECKOUT,
        ],
        ab_tests: [],
    },
};

export const LATEST_INTAKE_VERSIONS: LatestIntakeSpecification = {
    standard: { route_array: STANDARD_INTAKE_ROUTES, latest_version: 1 },
    glutathione: { route_array: GLUTATHIONE_INTAKE_ROUTES, latest_version: 1 },
    b12: { route_array: B12_INTAKE_ROUTES, latest_version: 2 },
    skincare: { route_array: SKINCARE_INTAKE_ROUTES, latest_version: 2 },
    nad: { route_array: NAD_INTAKE_ROUTES, latest_version: 2 },
    weight_loss: { route_array: WL_INTAKE_ROUTES, latest_version: 3 }, //deprecated
    combined_weight_loss: {
        route_array: COMBINED_WEIGHT_LOSS_ROUTES,
        latest_version: 2,
    },
    global_wl: { route_array: GLOBAL_WL_ROUTES, latest_version: 1 },
    semaglutide: { route_array: SEMAGLUTIDE_ROUTES, latest_version: 1 },
    tirzepatide: { route_array: TIRZEPATIDE_ROUTES, latest_version: 1 },
    metformin: { route_array: METFORMIN_INTAKE_ROUTES, latest_version: 1 },
    nad_nasal: {
        route_array: NAD_NASAL_SPRAY_INTAKE_ROUTES,
        latest_version: 1,
    },
    ed: {
        route_array: ED_GLOBAL_INTAKE_ROUTES,
        latest_version: 1,
    },
    'peak-chews': {
        route_array: ED_PRODUCT_INTAKE_ROUTES,
        latest_version: 1,
    },
    'rush-chews': {
        route_array: ED_PRODUCT_INTAKE_ROUTES,
        latest_version: 1,
    },
    'rush-melts': {
        route_array: RUSH_MELTS_INTAKE_ROUTES,
        latest_version: 1,
    },
    'x-melts': {
        route_array: ED_X_PRODUCTS_INTAKE_ROUTES,
        latest_version: 1,
    },
    'x-chews': {
        route_array: ED_X_PRODUCTS_INTAKE_ROUTES,
        latest_version: 1,
    },
    sermorelin: {
        latest_version: 1,
        route_array: SERMORELIN_ROUTES,
    },
};
