import { PRODUCT_HREF } from '../../global/product-enumerator';

export enum RudderstackEventType {
    Track = 'Track',
    Identify = 'Identify',
    Alias = 'Alias',
}

export enum RudderstackEvent {
    // Customer.io Events
    ACCOUNT_CREATED = 'account-created',
    ADDRESS_VERIFIED = 'address-verified',
    COMPLETE_PROFILE_SCREEN = 'complete-profile-screen',
    ORDER_RECEIVED = 'order-received',
    PURCHASE_SUCCESS = 'purchase-success',
    NEW_MESSAGE = 'new-message',
    PAYMENT_FAILED = 'failed-payment',
    PAYMENT_SUCCESS = 'payment-success',
    PRESCRIPTION_DELIVERED = 'prescription-delivered',
    PRESCRIPTION_PROCESSED = 'prescription-processed',
    PRESCRIPTION_APPROVED = 'prescription-approved',
    PRESCRIPTION_SHIPPED = 'prescription-shipped',
    ISSUE_WITH_DELIVERY = 'issue-with-delivery',
    PASSWORD_UPDATED = 'password-updated',
    ID_VERIFICATION_SKIPPED = 'id-skipped',
    SELFIE_SKIPPED = 'selfie-skipped',
    SELFIE_UPLOADED = 'selfie-uploaded',
    ID_VERIFICATION_UPLOADED = 'id-uploaded',
    CHECKIN_NEEDED = 'checkin-needed',
    WL_CHECKIN = 'wl-checkin',
    WL_CHECKIN_COMPLETE = 'wl-checkin-complete',
    WL_CHECKIN_INCOMPLETE = 'wl-checkin-incomplete',
    WL_CHECKIN_ELSE_PAUSED = 'wl-checkin-else-paused',
    WL_MULTI_MONTH_CHECKIN = 'wl-multi-month-check-in',
    WL_CHECKIN_RESEND = 'wl-checkin-resend',
    SUBSCRIPTION_CANCELED = 'subscription-canceled',
    WL_CHECKIN_UNPAID = 'wl-checkin-unpaid',
    WL_NEED_CHECKIN_UNPAID = 'wl-need-checkin-unpaid',
    WL_PAID = 'wl-paid',
    WL_UNPAID = 'wl-unpaid',
    ORDER_CONFIRMED = 'order-confirmed',
    ORDER_CANCELED = 'order-canceled',
    RENEWAL_ORDER_RECEIVED = 'renewal-order-received',
    PRESCRIPTION_RENEWAL_SHIPPED = 'prescription-renewal-shipped',
    CHECKOUT_REACHED_GENERAL = 'checkout-reached',
    NEW_NONPHI_MESSAGE = 'new-nonphi-message',
    NEW_BUG = 'new-bug',
    REQUIRES_ID_VERIFICATION = 'requires-id-verification',
    ID_VERIFICATION_COMPLETE = 'id-verification-complete',
    MESSAGE_UNREAD = 'message-unread',
    MESSAGE_REPLIED = 'message-replied',
    ID_VERIFICATION_FOLLOWUP = 'id-verification-followup',
    ID_VERIFICATION_FOLLOWUP_COMPLETE = 'id-verification-followup-complete',
    WL_IMMEDIATE = 'wl-multi-month-immediate',
    WL_ONE_WEEK = 'wl-one-week',
    WL_TWO_WEEKS = 'wl-two-weeks',
    ESCALATE_ORDER = 'escalate-order',
    SIGNUP_VIEWED = 'signup-viewed',
    INTAKE_COMPLETED = 'intake-completed',
    LEAD = 'lead',
    ORDER_CONFIRM = 'order-confirm',
    LEAD_STARTED = 'Lead',
    PROFILE_INTAKE_COMPLETED = 'profile-intake-completed',
    ID_VERIFICATION_REACHED = 'id-verification-reached',
    ID_VERIFICATION_COMPLETED = 'id-verification-completed',
    SELFIE_REACHED = 'selfie-reached',
    SELFIE_COMPLETED = 'selfie-completed',
    CHECKOUT_REACHED = 'checkout-reached',
    CHECKOUT_COMPLETED = 'checkout-completed',
    BUNDLE_SCREEN_VIEWED = 'bundle-screen-viewed',
    REFILL_DATE_CHANGED = 'refill-date-changed',
    FIRST_TIME_DOSAGE_SELECTION_COMPLETE = 'first-time-dosage-selection-complete',
    ED_SELECTION_VIEWED = 'ed-selection-viewed',
    //Adding an event as a test.
    NSIG_BIOVERSE = 'nsig-bioverse',
    WL_REACTIVATION_CHECKIN_REMINDER = 'wl-reactivation-checkin-reminder',
    BOOTHWYN_ESCALATE = 'boothwyn-escalate',
    REVIVE_ESCALATE = 'revive-escalate',
    CUREXA_ESCALATE = 'curexa-escalate',

    //ADDED BY BEN FOR BV2766
    PRESCRIPTION_DENIED = 'prescription-denied',
    DOSAGE_SUGGESTIONS_SENT = 'dosage-suggestions-sent', //in the renewal flow, when a provider approves 1-2 dosages for the patient, triggering dosage selection link macro send
    SUPER_SATISFIED_CUSTOMER = 'super-satisfied-customer',
}

export type ProductLeads = `${PRODUCT_HREF}-lead`;
export type ProductOrderConfirm = `${PRODUCT_HREF}-order-confirm`;
